/**
 * This class is generated by jOOQ
 */
package info.gngr.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionsRecord extends org.jooq.impl.UpdatableRecordImpl<info.gngr.db.tables.records.PermissionsRecord> implements org.jooq.Record3<java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 345032996;

	/**
	 * Setter for <code>PUBLIC.PERMISSIONS.FRAMEHOST</code>.
	 */
	public void setFramehost(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.PERMISSIONS.FRAMEHOST</code>.
	 */
	public java.lang.String getFramehost() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.PERMISSIONS.REQUESTHOST</code>.
	 */
	public void setRequesthost(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.PERMISSIONS.REQUESTHOST</code>.
	 */
	public java.lang.String getRequesthost() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.PERMISSIONS.PERMISSIONS</code>.
	 */
	public void setPermissions(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.PERMISSIONS.PERMISSIONS</code>.
	 */
	public java.lang.Integer getPermissions() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return info.gngr.db.tables.Permissions.PERMISSIONS.FRAMEHOST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return info.gngr.db.tables.Permissions.PERMISSIONS.REQUESTHOST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return info.gngr.db.tables.Permissions.PERMISSIONS.PERMISSIONS_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getFramehost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getRequesthost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getPermissions();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionsRecord value1(java.lang.String value) {
		setFramehost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionsRecord value2(java.lang.String value) {
		setRequesthost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionsRecord value3(java.lang.Integer value) {
		setPermissions(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermissionsRecord values(java.lang.String value1, java.lang.String value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PermissionsRecord
	 */
	public PermissionsRecord() {
		super(info.gngr.db.tables.Permissions.PERMISSIONS);
	}

	/**
	 * Create a detached, initialised PermissionsRecord
	 */
	public PermissionsRecord(java.lang.String framehost, java.lang.String requesthost, java.lang.Integer permissions) {
		super(info.gngr.db.tables.Permissions.PERMISSIONS);

		setValue(0, framehost);
		setValue(1, requesthost);
		setValue(2, permissions);
	}
}
