/**
 * This class is generated by jOOQ
 */
package info.gngr.db;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<info.gngr.db.tables.records.PermissionsRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<info.gngr.db.tables.records.PermissionsRecord> CONSTRAINT_C = createUniqueKey(info.gngr.db.tables.Permissions.PERMISSIONS, info.gngr.db.tables.Permissions.PERMISSIONS.FRAMEHOST, info.gngr.db.tables.Permissions.PERMISSIONS.REQUESTHOST);
	}
}
