/**
 * This class is generated by jOOQ
 */
package info.gngr.db;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.PERMISSIONS
	 */
	public static final info.gngr.db.tables.Permissions PERMISSIONS = info.gngr.db.tables.Permissions.PERMISSIONS;
}
